version: '3.9'

services:
  postgres_hw:
    image: postgres:17.5
    env_file: .env
    restart: always
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 30
