// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pwz/pwz.proto

package pwz

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_PRIORITY_UNKNOWN Priority = 0
	Priority_PRIORITY_MIN     Priority = 1
	Priority_PRIORITY_LOW     Priority = 2
	Priority_PRIORITY_DEFAULT Priority = 3
	Priority_PRIORITY_HIGH    Priority = 4
	Priority_PRIORITY_MAX     Priority = 5
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNKNOWN",
		1: "PRIORITY_MIN",
		2: "PRIORITY_LOW",
		3: "PRIORITY_DEFAULT",
		4: "PRIORITY_HIGH",
		5: "PRIORITY_MAX",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNKNOWN": 0,
		"PRIORITY_MIN":     1,
		"PRIORITY_LOW":     2,
		"PRIORITY_DEFAULT": 3,
		"PRIORITY_HIGH":    4,
		"PRIORITY_MAX":     5,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_pwz_pwz_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_pwz_pwz_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{0}
}

type ActionType int32

const (
	// не указан
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	// выдать заказы
	ActionType_ACTION_TYPE_ISSUE ActionType = 1
	// принять возврат клиента
	ActionType_ACTION_TYPE_RETURN ActionType = 2
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_ISSUE",
		2: "ACTION_TYPE_RETURN",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ACTION_TYPE_ISSUE":       1,
		"ACTION_TYPE_RETURN":      2,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pwz_pwz_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_pwz_pwz_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{1}
}

type PackageType int32

const (
	// не указан
	PackageType_PACKAGE_TYPE_UNSPECIFIED PackageType = 0
	// пакет
	PackageType_PACKAGE_TYPE_BAG PackageType = 1
	// коробка
	PackageType_PACKAGE_TYPE_BOX PackageType = 2
	// пленка
	PackageType_PACKAGE_TYPE_TAPE PackageType = 3
	// пленка + пакет
	PackageType_PACKAGE_TYPE_BAG_TAPE PackageType = 4
	// пленка + коробка
	PackageType_PACKAGE_TYPE_BOX_TAPE PackageType = 5
)

// Enum value maps for PackageType.
var (
	PackageType_name = map[int32]string{
		0: "PACKAGE_TYPE_UNSPECIFIED",
		1: "PACKAGE_TYPE_BAG",
		2: "PACKAGE_TYPE_BOX",
		3: "PACKAGE_TYPE_TAPE",
		4: "PACKAGE_TYPE_BAG_TAPE",
		5: "PACKAGE_TYPE_BOX_TAPE",
	}
	PackageType_value = map[string]int32{
		"PACKAGE_TYPE_UNSPECIFIED": 0,
		"PACKAGE_TYPE_BAG":         1,
		"PACKAGE_TYPE_BOX":         2,
		"PACKAGE_TYPE_TAPE":        3,
		"PACKAGE_TYPE_BAG_TAPE":    4,
		"PACKAGE_TYPE_BOX_TAPE":    5,
	}
)

func (x PackageType) Enum() *PackageType {
	p := new(PackageType)
	*p = x
	return p
}

func (x PackageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pwz_pwz_proto_enumTypes[2].Descriptor()
}

func (PackageType) Type() protoreflect.EnumType {
	return &file_pwz_pwz_proto_enumTypes[2]
}

func (x PackageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageType.Descriptor instead.
func (PackageType) EnumDescriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{2}
}

type OrderStatus int32

const (
	// не указан
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	// получен, ожидает выдачи клиенту
	OrderStatus_ORDER_STATUS_EXPECTS OrderStatus = 1
	// выдан клиенту
	OrderStatus_ORDER_STATUS_ACCEPTED OrderStatus = 2
	// возвращен клиентом в пвз
	OrderStatus_ORDER_STATUS_RETURNED OrderStatus = 3
	// возвращен курьеру из пвз
	OrderStatus_ORDER_STATUS_DELETED OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_EXPECTS",
		2: "ORDER_STATUS_ACCEPTED",
		3: "ORDER_STATUS_RETURNED",
		4: "ORDER_STATUS_DELETED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_EXPECTS":     1,
		"ORDER_STATUS_ACCEPTED":    2,
		"ORDER_STATUS_RETURNED":    3,
		"ORDER_STATUS_DELETED":     4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pwz_pwz_proto_enumTypes[3].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_pwz_pwz_proto_enumTypes[3]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{3}
}

// было для тестов
type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Priority      Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=notifier.Priority" json:"priority,omitempty"`
	Delay         *durationpb.Duration   `protobuf:"bytes,3,opt,name=delay,proto3" json:"delay,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Comment       *string                `protobuf:"bytes,5,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_pwz_pwz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNKNOWN
}

func (x *MessageRequest) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *MessageRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MessageRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *MessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_pwz_pwz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TODO:новые сообщения
type OrderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistoryRequest) Reset() {
	*x = OrderHistoryRequest{}
	mi := &file_pwz_pwz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistoryRequest) ProtoMessage() {}

func (x *OrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*OrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{2}
}

func (x *OrderHistoryRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*OrderHistory        `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistoryResponse) Reset() {
	*x = OrderHistoryResponse{}
	mi := &file_pwz_pwz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistoryResponse) ProtoMessage() {}

func (x *OrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*OrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{3}
}

func (x *OrderHistoryResponse) GetHistory() []*OrderHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type AcceptOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Package       *PackageType           `protobuf:"varint,4,opt,name=package,proto3,enum=notifier.PackageType,oneof" json:"package,omitempty"`
	Weight        float32                `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_pwz_pwz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AcceptOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AcceptOrderRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AcceptOrderRequest) GetPackage() PackageType {
	if x != nil && x.Package != nil {
		return *x.Package
	}
	return PackageType_PACKAGE_TYPE_UNSPECIFIED
}

func (x *AcceptOrderRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *AcceptOrderRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type OrderIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderIdRequest) Reset() {
	*x = OrderIdRequest{}
	mi := &file_pwz_pwz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderIdRequest) ProtoMessage() {}

func (x *OrderIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderIdRequest.ProtoReflect.Descriptor instead.
func (*OrderIdRequest) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{5}
}

func (x *OrderIdRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ProcessOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        ActionType             `protobuf:"varint,2,opt,name=action,proto3,enum=notifier.ActionType" json:"action,omitempty"`
	OrderIds      []uint64               `protobuf:"varint,3,rep,packed,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessOrdersRequest) Reset() {
	*x = ProcessOrdersRequest{}
	mi := &file_pwz_pwz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOrdersRequest) ProtoMessage() {}

func (x *ProcessOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOrdersRequest.ProtoReflect.Descriptor instead.
func (*ProcessOrdersRequest) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessOrdersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProcessOrdersRequest) GetAction() ActionType {
	if x != nil {
		return x.Action
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ProcessOrdersRequest) GetOrderIds() []uint64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InPvz         bool                   `protobuf:"varint,2,opt,name=in_pvz,json=inPvz,proto3" json:"in_pvz,omitempty"` // если true, то будут заказы для выдачи клиенту, если false, то все
	LastN         *uint32                `protobuf:"varint,3,opt,name=last_n,json=lastN,proto3,oneof" json:"last_n,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_pwz_pwz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrdersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersRequest) GetInPvz() bool {
	if x != nil {
		return x.InPvz
	}
	return false
}

func (x *ListOrdersRequest) GetLastN() uint32 {
	if x != nil && x.LastN != nil {
		return *x.LastN
	}
	return 0
}

func (x *ListOrdersRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	CountOnPage   uint32                 `protobuf:"varint,2,opt,name=count_on_page,json=countOnPage,proto3" json:"count_on_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_pwz_pwz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{8}
}

func (x *Pagination) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetCountOnPage() uint32 {
	if x != nil {
		return x.CountOnPage
	}
	return 0
}

type ListReturnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReturnsRequest) Reset() {
	*x = ListReturnsRequest{}
	mi := &file_pwz_pwz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReturnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReturnsRequest) ProtoMessage() {}

func (x *ListReturnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReturnsRequest.ProtoReflect.Descriptor instead.
func (*ListReturnsRequest) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{9}
}

func (x *ListReturnsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ImportOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*AcceptOrderRequest  `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportOrdersRequest) Reset() {
	*x = ImportOrdersRequest{}
	mi := &file_pwz_pwz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportOrdersRequest) ProtoMessage() {}

func (x *ImportOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportOrdersRequest.ProtoReflect.Descriptor instead.
func (*ImportOrdersRequest) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{10}
}

func (x *ImportOrdersRequest) GetOrders() []*AcceptOrderRequest {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_pwz_pwz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{11}
}

func (x *GetHistoryRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OrderStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=notifier.OrderStatus" json:"status,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_pwz_pwz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{12}
}

func (x *OrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderResponse) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ProcessResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processed     []uint64               `protobuf:"varint,1,rep,packed,name=processed,proto3" json:"processed,omitempty"`
	Errors        []uint64               `protobuf:"varint,2,rep,packed,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResult) Reset() {
	*x = ProcessResult{}
	mi := &file_pwz_pwz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResult) ProtoMessage() {}

func (x *ProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResult.ProtoReflect.Descriptor instead.
func (*ProcessResult) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{13}
}

func (x *ProcessResult) GetProcessed() []uint64 {
	if x != nil {
		return x.Processed
	}
	return nil
}

func (x *ProcessResult) GetErrors() []uint64 {
	if x != nil {
		return x.Errors
	}
	return nil
}

type OrdersList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersList) Reset() {
	*x = OrdersList{}
	mi := &file_pwz_pwz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersList) ProtoMessage() {}

func (x *OrdersList) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersList.ProtoReflect.Descriptor instead.
func (*OrdersList) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{14}
}

func (x *OrdersList) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *OrdersList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReturnsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Returns       []*Order               `protobuf:"bytes,1,rep,name=returns,proto3" json:"returns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnsList) Reset() {
	*x = ReturnsList{}
	mi := &file_pwz_pwz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnsList) ProtoMessage() {}

func (x *ReturnsList) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnsList.ProtoReflect.Descriptor instead.
func (*ReturnsList) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{15}
}

func (x *ReturnsList) GetReturns() []*Order {
	if x != nil {
		return x.Returns
	}
	return nil
}

type OrderHistoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*OrderHistory        `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistoryList) Reset() {
	*x = OrderHistoryList{}
	mi := &file_pwz_pwz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistoryList) ProtoMessage() {}

func (x *OrderHistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistoryList.ProtoReflect.Descriptor instead.
func (*OrderHistoryList) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{16}
}

func (x *OrderHistoryList) GetHistory() []*OrderHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type ImportResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imported      int32                  `protobuf:"varint,1,opt,name=imported,proto3" json:"imported,omitempty"`
	Errors        []uint64               `protobuf:"varint,2,rep,packed,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResult) Reset() {
	*x = ImportResult{}
	mi := &file_pwz_pwz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResult) ProtoMessage() {}

func (x *ImportResult) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResult.ProtoReflect.Descriptor instead.
func (*ImportResult) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{17}
}

func (x *ImportResult) GetImported() int32 {
	if x != nil {
		return x.Imported
	}
	return 0
}

func (x *ImportResult) GetErrors() []uint64 {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=notifier.OrderStatus" json:"status,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Weight        float32                `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Package       *PackageType           `protobuf:"varint,7,opt,name=package,proto3,enum=notifier.PackageType,oneof" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_pwz_pwz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{18}
}

func (x *Order) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Order) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Order) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetPackage() PackageType {
	if x != nil && x.Package != nil {
		return *x.Package
	}
	return PackageType_PACKAGE_TYPE_UNSPECIFIED
}

type OrderHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=notifier.OrderStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistory) Reset() {
	*x = OrderHistory{}
	mi := &file_pwz_pwz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistory) ProtoMessage() {}

func (x *OrderHistory) ProtoReflect() protoreflect.Message {
	mi := &file_pwz_pwz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistory.ProtoReflect.Descriptor instead.
func (*OrderHistory) Descriptor() ([]byte, []int) {
	return file_pwz_pwz_proto_rawDescGZIP(), []int{19}
}

func (x *OrderHistory) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderHistory) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_pwz_pwz_proto protoreflect.FileDescriptor

const file_pwz_pwz_proto_rawDesc = "" +
	"\n" +
	"\rpwz/pwz.proto\x12\bnotifier\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x83\x02\n" +
	"\x0eMessageRequest\x12\x1e\n" +
	"\x04text\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x04text\x128\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x12.notifier.PriorityB\b\xfaB\x05\x82\x01\x02\x10\x01R\bpriority\x12/\n" +
	"\x05delay\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x05delay\x12\x1c\n" +
	"\x04tags\x18\x04 \x03(\tB\b\xfaB\x05\x92\x01\x02\x10\n" +
	"R\x04tags\x12\x1d\n" +
	"\acomment\x18\x05 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x1d\n" +
	"\x05title\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x182R\x05titleB\n" +
	"\n" +
	"\b_comment\"!\n" +
	"\x0fMessageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"0\n" +
	"\x13OrderHistoryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"H\n" +
	"\x14OrderHistoryResponse\x120\n" +
	"\ahistory\x18\x01 \x03(\v2\x16.notifier.OrderHistoryR\ahistory\"\x8b\x02\n" +
	"\x12AcceptOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x124\n" +
	"\apackage\x18\x04 \x01(\x0e2\x15.notifier.PackageTypeH\x00R\apackage\x88\x01\x01\x12\"\n" +
	"\x06weight\x18\x05 \x01(\x02B\n" +
	"\xfaB\a\n" +
	"\x05%\x00\x00\x00\x00R\x06weight\x12 \n" +
	"\x05price\x18\x06 \x01(\x02B\n" +
	"\xfaB\a\n" +
	"\x05-\x00\x00\x00\x00R\x05priceB\n" +
	"\n" +
	"\b_package\"+\n" +
	"\x0eOrderIdRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"z\n" +
	"\x14ProcessOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.notifier.ActionTypeR\x06action\x12\x1b\n" +
	"\torder_ids\x18\x03 \x03(\x04R\borderIds\"\xb4\x01\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06in_pvz\x18\x02 \x01(\bR\x05inPvz\x12\x1a\n" +
	"\x06last_n\x18\x03 \x01(\rH\x00R\x05lastN\x88\x01\x01\x129\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x14.notifier.PaginationH\x01R\n" +
	"pagination\x88\x01\x01B\t\n" +
	"\a_last_nB\r\n" +
	"\v_pagination\"X\n" +
	"\n" +
	"Pagination\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\rB\a\xfaB\x04*\x02(\x00R\x04page\x12-\n" +
	"\rcount_on_page\x18\x02 \x01(\rB\t\xfaB\x06*\x04\x18d(\x00R\vcountOnPage\"J\n" +
	"\x12ListReturnsRequest\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.notifier.PaginationR\n" +
	"pagination\"U\n" +
	"\x13ImportOrdersRequest\x12>\n" +
	"\x06orders\x18\x01 \x03(\v2\x1c.notifier.AcceptOrderRequestB\b\xfaB\x05\x92\x01\x02\b\x01R\x06orders\"I\n" +
	"\x11GetHistoryRequest\x124\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x14.notifier.PaginationR\n" +
	"pagination\"Y\n" +
	"\rOrderResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.notifier.OrderStatusR\x06status\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\"E\n" +
	"\rProcessResult\x12\x1c\n" +
	"\tprocessed\x18\x01 \x03(\x04R\tprocessed\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\x04R\x06errors\"T\n" +
	"\n" +
	"OrdersList\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.notifier.OrderR\x06orders\x12\x1d\n" +
	"\x05total\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x05total\"8\n" +
	"\vReturnsList\x12)\n" +
	"\areturns\x18\x01 \x03(\v2\x0f.notifier.OrderR\areturns\"D\n" +
	"\x10OrderHistoryList\x120\n" +
	"\ahistory\x18\x01 \x03(\v2\x16.notifier.OrderHistoryR\ahistory\"K\n" +
	"\fImportResult\x12#\n" +
	"\bimported\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\bimported\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\x04R\x06errors\"\xb8\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.notifier.OrderStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\"\n" +
	"\x06weight\x18\x05 \x01(\x02B\n" +
	"\xfaB\a\n" +
	"\x05%\x00\x00\x00\x00R\x06weight\x12+\n" +
	"\vtotal_price\x18\x06 \x01(\x02B\n" +
	"\xfaB\a\n" +
	"\x05-\x00\x00\x00\x00R\n" +
	"totalPrice\x124\n" +
	"\apackage\x18\a \x01(\x0e2\x15.notifier.PackageTypeH\x00R\apackage\x88\x01\x01B\n" +
	"\n" +
	"\b_package\"\x93\x01\n" +
	"\fOrderHistory\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.notifier.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*\x7f\n" +
	"\bPriority\x12\x14\n" +
	"\x10PRIORITY_UNKNOWN\x10\x00\x12\x10\n" +
	"\fPRIORITY_MIN\x10\x01\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x02\x12\x14\n" +
	"\x10PRIORITY_DEFAULT\x10\x03\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x04\x12\x10\n" +
	"\fPRIORITY_MAX\x10\x05*X\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_TYPE_ISSUE\x10\x01\x12\x16\n" +
	"\x12ACTION_TYPE_RETURN\x10\x02*\xa4\x01\n" +
	"\vPackageType\x12\x1c\n" +
	"\x18PACKAGE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PACKAGE_TYPE_BAG\x10\x01\x12\x14\n" +
	"\x10PACKAGE_TYPE_BOX\x10\x02\x12\x15\n" +
	"\x11PACKAGE_TYPE_TAPE\x10\x03\x12\x19\n" +
	"\x15PACKAGE_TYPE_BAG_TAPE\x10\x04\x12\x19\n" +
	"\x15PACKAGE_TYPE_BOX_TAPE\x10\x05*\x95\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_EXPECTS\x10\x01\x12\x19\n" +
	"\x15ORDER_STATUS_ACCEPTED\x10\x02\x12\x19\n" +
	"\x15ORDER_STATUS_RETURNED\x10\x03\x12\x18\n" +
	"\x14ORDER_STATUS_DELETED\x10\x042\xd5\f\n" +
	"\bNotifier\x12s\n" +
	"\vSendMessage\x12\x18.notifier.MessageRequest\x1a\x19.notifier.MessageResponse\"/\x92A\x15\x1a\x13Описание...\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/SendMessage\x12\xa5\x01\n" +
	"\vAcceptOrder\x12\x1c.notifier.AcceptOrderRequest\x1a\x17.notifier.OrderResponse\"_\x92AD\x12-Принять заказ от курьера\x1a\x13Описание...\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/accept_order\x12\x9c\x01\n" +
	"\vReturnOrder\x12\x18.notifier.OrderIdRequest\x1a\x17.notifier.OrderResponse\"Z\x92A?\x12(Вернуть заказ курьеру\x1a\x13Описание...\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/return_order\x12\xcc\x01\n" +
	"\rProcessOrders\x12\x1e.notifier.ProcessOrdersRequest\x1a\x17.notifier.ProcessResult\"\x81\x01\x92Ad\x12MВыдать заказы или принять возврат клиента\x1a\x13Описание...\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/process_orders\x12\x9e\x01\n" +
	"\n" +
	"ListOrders\x12\x1b.notifier.ListOrdersRequest\x1a\x14.notifier.OrdersList\"]\x92AC\x12,Получить список заказов\x1a\x13Описание...\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/list_orders\x12\xa6\x01\n" +
	"\vListReturns\x12\x1c.notifier.ListReturnsRequest\x1a\x15.notifier.ReturnsList\"b\x92AG\x120Получить список возвратов\x1a\x13Описание...\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/list_returns\x12\xb9\x01\n" +
	"\n" +
	"GetHistory\x12\x1b.notifier.GetHistoryRequest\x1a\x1a.notifier.OrderHistoryList\"r\x92AX\x12AПолучить историю изменения заказов\x1a\x13Описание...\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/get_history\x12\xf6\x01\n" +
	"\fImportOrders\x12\x1d.notifier.ImportOrdersRequest\x1a\x16.notifier.ImportResult\"\xae\x01\x92A\x91\x01\x12zИмпорт заказов (если эта ручка делалась ранее в рамках доп заданий)\x1a\x13Описание...\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/import_orders\x12\xbe\x01\n" +
	"\x0fGetOrderHistory\x12\x1d.notifier.OrderHistoryRequest\x1a\x1e.notifier.OrderHistoryResponse\"l\x92AH\x121Получить историю по заказу\x1a\x13Описание...\x82\xd3\xe4\x93\x02\x1b\x12\x19/order/{order_id}/historyB\x8a\x01\x92Aw\x12=\n" +
	"&Пункт выдачи заказов\x12\fHTTP и gRPC2\x051.0.0\x1a\x0flocalhost:50052*\x01\x012\x10application/json:\x10application/jsonZ\x0ePWZ1.0/pkg/pwzb\x06proto3"

var (
	file_pwz_pwz_proto_rawDescOnce sync.Once
	file_pwz_pwz_proto_rawDescData []byte
)

func file_pwz_pwz_proto_rawDescGZIP() []byte {
	file_pwz_pwz_proto_rawDescOnce.Do(func() {
		file_pwz_pwz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pwz_pwz_proto_rawDesc), len(file_pwz_pwz_proto_rawDesc)))
	})
	return file_pwz_pwz_proto_rawDescData
}

var file_pwz_pwz_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pwz_pwz_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pwz_pwz_proto_goTypes = []any{
	(Priority)(0),                 // 0: notifier.Priority
	(ActionType)(0),               // 1: notifier.ActionType
	(PackageType)(0),              // 2: notifier.PackageType
	(OrderStatus)(0),              // 3: notifier.OrderStatus
	(*MessageRequest)(nil),        // 4: notifier.MessageRequest
	(*MessageResponse)(nil),       // 5: notifier.MessageResponse
	(*OrderHistoryRequest)(nil),   // 6: notifier.OrderHistoryRequest
	(*OrderHistoryResponse)(nil),  // 7: notifier.OrderHistoryResponse
	(*AcceptOrderRequest)(nil),    // 8: notifier.AcceptOrderRequest
	(*OrderIdRequest)(nil),        // 9: notifier.OrderIdRequest
	(*ProcessOrdersRequest)(nil),  // 10: notifier.ProcessOrdersRequest
	(*ListOrdersRequest)(nil),     // 11: notifier.ListOrdersRequest
	(*Pagination)(nil),            // 12: notifier.Pagination
	(*ListReturnsRequest)(nil),    // 13: notifier.ListReturnsRequest
	(*ImportOrdersRequest)(nil),   // 14: notifier.ImportOrdersRequest
	(*GetHistoryRequest)(nil),     // 15: notifier.GetHistoryRequest
	(*OrderResponse)(nil),         // 16: notifier.OrderResponse
	(*ProcessResult)(nil),         // 17: notifier.ProcessResult
	(*OrdersList)(nil),            // 18: notifier.OrdersList
	(*ReturnsList)(nil),           // 19: notifier.ReturnsList
	(*OrderHistoryList)(nil),      // 20: notifier.OrderHistoryList
	(*ImportResult)(nil),          // 21: notifier.ImportResult
	(*Order)(nil),                 // 22: notifier.Order
	(*OrderHistory)(nil),          // 23: notifier.OrderHistory
	(*durationpb.Duration)(nil),   // 24: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
}
var file_pwz_pwz_proto_depIdxs = []int32{
	0,  // 0: notifier.MessageRequest.priority:type_name -> notifier.Priority
	24, // 1: notifier.MessageRequest.delay:type_name -> google.protobuf.Duration
	23, // 2: notifier.OrderHistoryResponse.history:type_name -> notifier.OrderHistory
	25, // 3: notifier.AcceptOrderRequest.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 4: notifier.AcceptOrderRequest.package:type_name -> notifier.PackageType
	1,  // 5: notifier.ProcessOrdersRequest.action:type_name -> notifier.ActionType
	12, // 6: notifier.ListOrdersRequest.pagination:type_name -> notifier.Pagination
	12, // 7: notifier.ListReturnsRequest.pagination:type_name -> notifier.Pagination
	8,  // 8: notifier.ImportOrdersRequest.orders:type_name -> notifier.AcceptOrderRequest
	12, // 9: notifier.GetHistoryRequest.pagination:type_name -> notifier.Pagination
	3,  // 10: notifier.OrderResponse.status:type_name -> notifier.OrderStatus
	22, // 11: notifier.OrdersList.orders:type_name -> notifier.Order
	22, // 12: notifier.ReturnsList.returns:type_name -> notifier.Order
	23, // 13: notifier.OrderHistoryList.history:type_name -> notifier.OrderHistory
	3,  // 14: notifier.Order.status:type_name -> notifier.OrderStatus
	25, // 15: notifier.Order.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 16: notifier.Order.package:type_name -> notifier.PackageType
	3,  // 17: notifier.OrderHistory.status:type_name -> notifier.OrderStatus
	25, // 18: notifier.OrderHistory.created_at:type_name -> google.protobuf.Timestamp
	4,  // 19: notifier.Notifier.SendMessage:input_type -> notifier.MessageRequest
	8,  // 20: notifier.Notifier.AcceptOrder:input_type -> notifier.AcceptOrderRequest
	9,  // 21: notifier.Notifier.ReturnOrder:input_type -> notifier.OrderIdRequest
	10, // 22: notifier.Notifier.ProcessOrders:input_type -> notifier.ProcessOrdersRequest
	11, // 23: notifier.Notifier.ListOrders:input_type -> notifier.ListOrdersRequest
	13, // 24: notifier.Notifier.ListReturns:input_type -> notifier.ListReturnsRequest
	15, // 25: notifier.Notifier.GetHistory:input_type -> notifier.GetHistoryRequest
	14, // 26: notifier.Notifier.ImportOrders:input_type -> notifier.ImportOrdersRequest
	6,  // 27: notifier.Notifier.GetOrderHistory:input_type -> notifier.OrderHistoryRequest
	5,  // 28: notifier.Notifier.SendMessage:output_type -> notifier.MessageResponse
	16, // 29: notifier.Notifier.AcceptOrder:output_type -> notifier.OrderResponse
	16, // 30: notifier.Notifier.ReturnOrder:output_type -> notifier.OrderResponse
	17, // 31: notifier.Notifier.ProcessOrders:output_type -> notifier.ProcessResult
	18, // 32: notifier.Notifier.ListOrders:output_type -> notifier.OrdersList
	19, // 33: notifier.Notifier.ListReturns:output_type -> notifier.ReturnsList
	20, // 34: notifier.Notifier.GetHistory:output_type -> notifier.OrderHistoryList
	21, // 35: notifier.Notifier.ImportOrders:output_type -> notifier.ImportResult
	7,  // 36: notifier.Notifier.GetOrderHistory:output_type -> notifier.OrderHistoryResponse
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pwz_pwz_proto_init() }
func file_pwz_pwz_proto_init() {
	if File_pwz_pwz_proto != nil {
		return
	}
	file_pwz_pwz_proto_msgTypes[0].OneofWrappers = []any{}
	file_pwz_pwz_proto_msgTypes[4].OneofWrappers = []any{}
	file_pwz_pwz_proto_msgTypes[7].OneofWrappers = []any{}
	file_pwz_pwz_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pwz_pwz_proto_rawDesc), len(file_pwz_pwz_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pwz_pwz_proto_goTypes,
		DependencyIndexes: file_pwz_pwz_proto_depIdxs,
		EnumInfos:         file_pwz_pwz_proto_enumTypes,
		MessageInfos:      file_pwz_pwz_proto_msgTypes,
	}.Build()
	File_pwz_pwz_proto = out.File
	file_pwz_pwz_proto_goTypes = nil
	file_pwz_pwz_proto_depIdxs = nil
}
